// Auto-generated by scripts/export-abis.ts
// Do not edit manually

export const Orchestrator_ABI = require('./Orchestrator.abi.json');
export const CreditMarket_ABI = require('./CreditMarket.abi.json');
export const LoanPositionToken_ABI = require('./LoanPositionToken.abi.json');
export const ITICSBridge_ABI = require('./ITICSBridge.abi.json');
export const TICSBridge_ABI = require('./TICSBridge.abi.json');
export const SanctionsSentinel_ABI = require('./SanctionsSentinel.abi.json');
export const PriceFeedAdapter_ABI = require('./PriceFeedAdapter.abi.json');


export interface Module2Contracts {
  Orchestrator: string;
  CreditMarket: string;
  LoanPositionToken: string;
  ITICSBridge: string;
  TICSBridge: string;
  SanctionsSentinel: string;
  PriceFeedAdapter: string;
}

export const CONTRACT_ADDRESSES: Module2Contracts = {
  // TODO: Fill in after deployment
  Orchestrator: process.env.ORCHESTRATOR_ADDRESS || '',
  CreditMarket: process.env.CREDIT_MARKET_ADDRESS || '',
  LoanPositionToken: process.env.LOAN_POSITION_TOKEN_ADDRESS || '',
  ITICSBridge: process.env.TICS_BRIDGE_ADDRESS || '',
  TICSBridge: process.env.TICS_BRIDGE_ADDRESS || '',
  SanctionsSentinel: process.env.SANCTIONS_SENTINEL_ADDRESS || '',
  PriceFeedAdapter: process.env.PRICE_FEED_ADAPTER_ADDRESS || '',
};

