import * as fs from 'fs';
import * as path from 'path';

const CONTRACTS = [
  { source: 'Orchestrator.sol/Orchestrator.json', output: 'Orchestrator.abi.json' },
  { source: 'CreditMarket.sol/CreditMarket.json', output: 'CreditMarket.abi.json' },
  { source: 'LoanPositionToken.sol/LoanPositionToken.json', output: 'LoanPositionToken.abi.json' },
  { source: 'interfaces/ITICSBridge.sol/ITICSBridge.json', output: 'ITICSBridge.abi.json' },
  { source: 'TICSBridge.sol/TICSBridge.json', output: 'TICSBridge.abi.json' },
  { source: 'SanctionsSentinel.sol/SanctionsSentinel.json', output: 'SanctionsSentinel.abi.json' },
  { source: 'PriceFeedAdapter.sol/PriceFeedAdapter.json', output: 'PriceFeedAdapter.abi.json' },
];

const ARTIFACTS_DIR = path.join(__dirname, '..', 'artifacts', 'contracts', 'module2');
const EXPORTS_DIR = path.join(__dirname, '..', 'exports', 'module2');

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function exportABI(contract: typeof CONTRACTS[0]) {
  const artifactPath = path.join(ARTIFACTS_DIR, contract.source);
  
  if (!fs.existsSync(artifactPath)) {
    console.error(`Artifact not found: ${artifactPath}`);
    return false;
  }
  
  const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
  const abiPath = path.join(EXPORTS_DIR, contract.output);
  
  fs.writeFileSync(abiPath, JSON.stringify(artifact.abi, null, 2));
  console.log(`Exported: ${contract.output}`);
  return true;
}

function generateTypeScriptIndex() {
  const exports = CONTRACTS.map(c => {
    const name = c.output.replace('.abi.json', '');
    return `export const ${name}_ABI = require('./${c.output}');`;
  });
  
  // Add contract addresses type
  const typeDefinition = `
export interface Module2Contracts {
  Orchestrator: string;
  CreditMarket: string;
  LoanPositionToken: string;
  ITICSBridge: string;
  TICSBridge: string;
  SanctionsSentinel: string;
  PriceFeedAdapter: string;
}

export const CONTRACT_ADDRESSES: Module2Contracts = {
  // TODO: Fill in after deployment
  Orchestrator: process.env.ORCHESTRATOR_ADDRESS || '',
  CreditMarket: process.env.CREDIT_MARKET_ADDRESS || '',
  LoanPositionToken: process.env.LOAN_POSITION_TOKEN_ADDRESS || '',
  ITICSBridge: process.env.TICS_BRIDGE_ADDRESS || '',
  TICSBridge: process.env.TICS_BRIDGE_ADDRESS || '',
  SanctionsSentinel: process.env.SANCTIONS_SENTINEL_ADDRESS || '',
  PriceFeedAdapter: process.env.PRICE_FEED_ADAPTER_ADDRESS || '',
};
`;
  
  const content = `// Auto-generated by scripts/export-abis.ts
// Do not edit manually

${exports.join('\n')}

${typeDefinition}
`;
  
  fs.writeFileSync(path.join(EXPORTS_DIR, 'index.ts'), content);
  console.log('Generated: index.ts');
}

function main() {
  console.log('Exporting Module 2 ABIs...\n');
  
  ensureDir(EXPORTS_DIR);
  
  let allExported = true;
  for (const contract of CONTRACTS) {
    if (!exportABI(contract)) {
      allExported = false;
    }
  }
  
  if (allExported) {
    generateTypeScriptIndex();
    console.log('\n✓ All ABIs exported successfully');
  } else {
    console.error('\n✗ Some ABIs failed to export');
    process.exit(1);
  }
}

main();
